apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-argocd # default namespace 
    server: 'https://kubernetes.default.svc'
  source:
    path: web
    repoURL: 'https://github.com/ky381011/argocd-test'
    #targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
      {{- with $.Values.valuesFile }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
  project: default
  syncPolicy:
    automated:
      prune: false