apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
spec:
  destination:
    namespace: sample
    server: 'https://kubernetes.default.svc'
  source:
    path: sample-app
    repoURL: '{GitのURL}'
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
      {{- with $.Values.valuesFile }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
  project: default
  syncPolicy:
    automated:
      prune: false